### ISSUE TITLE
publish a new release

### ISSUE THREAD

**Issue by maks** [arcticfox1919/LuaDardo#23]
Hi @arcticfox1919, would it be possible to publish a new release of this great package  to pub.dev? as the currently published `0.0.4` release doesn't contain 85a82918da6696885c4291da4c906230acf523cd which fixes the annoying null-safety warning messages.

**Comment by arcticfox1919** [comment]
I will take some time to fix a few issues and then push a new version.

**Comment by arcticfox1919** [comment]
v0.0.5
