### ISSUE TITLE
Can I expand to support SciDart?

### ISSUE THREAD

**Issue by polotto** [arcticfox1919/LuaDardo#6]
Amazing project, congratulations!

I have been searching for some interpreter written in Dart and so far your implementation is the best that I found!!!
I created a library called SciDart(https://scidart.org/) my intention is create a full and functional Scientific platform for Dart and to achieve this I need an interpreter. Can I use your implementation and extend to support SciDart?

**Comment by arcticfox1919** [comment]
@polotto 
Of course! It's just that LuaDardo is still experimental at the moment, and I don't have time for optimization and continued development of the Lua standard library at the moment to recommend it for use in release projects.

**Comment by arcticfox1919** [comment]
@polotto 
Of course!  It's just that LuaDardo is still experimental. I don't have time to optimize and continue to develop the Lua standard library. It is not recommended to use it in release projects.

**Comment by polotto** [comment]
Thank you! The SciDart is experimental as well, I think we are good.

**Comment by polotto** [comment]
Can you answer a question?
I trying bind SciDart with LuaDardo and I face this problem:

```dart
static int _sayHi(LuaState ls) {
    Person p = ls.toUserdata<Person>(1).data;
    if (ls.isString(-1)) {
     var result = p.sayHi(ls.toStr(-1));
     // How do I put this result back to Lua code?
    }
    return 0;
  }
```

How do I put the result that I get in Dart back to Lua?

**Comment by polotto** [comment]
Thank you!

**Comment by polotto** [comment]
Thank you! Is there some way to generate these binds automatically? That would be really amazing to make the integration with my library more easy.
